# Generated by Django 5.0.7 on 2024-07-30 13:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_sk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Model SK')),
                ('model_de', models.CharField(blank=True, max_length=255, null=True, verbose_name='Model DE')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zákazník')),
                ('pass_value', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=255, null=True, verbose_name='PASS')),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Dátum')),
                ('complaint_number', models.CharField(max_length=255, unique=True, verbose_name='Číslo reklamácie')),
                ('quantity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Počet kusov')),
                ('reason', models.TextField(blank=True, max_length=255, null=True, verbose_name='Dôvod')),
                ('activities', models.TextField(blank=True, max_length=255, null=True, verbose_name='Aktivity')),
                ('status', models.CharField(blank=True, choices=[('Akceptovaná', 'Akceptovaná'), ('Neakceptovaná', 'Neakceptovaná'), ('V procese', 'V procese'), ('Stornovaná', 'Stornovaná')], max_length=100, null=True, verbose_name='Stav')),
                ('response_date', models.DateField(blank=True, null=True, verbose_name='Dátum odpovede')),
                ('extra_note', models.TextField(blank=True, max_length=255, null=True, verbose_name='Poznámka')),
                ('correction_verification', models.TextField(blank=True, max_length=255, null=True, verbose_name='Overenie nápravných opatrení')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Celkové náklady')),
                ('highlighted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_complaints', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_external_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ComplainCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('our_costs', 'Our Costs'), ('without_costs', 'Without Costs')], max_length=15)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='complaints.externalcomplaint')),
            ],
        ),
        migrations.CreateModel(
            name='InternalComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Model')),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Dátum')),
                ('complaint_number', models.CharField(max_length=255, unique=True, verbose_name='Číslo reklamácie')),
                ('part_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Číslo súčiastky')),
                ('product_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Číslo výrobku')),
                ('priority', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True, verbose_name='Priorita')),
                ('reason', models.TextField(blank=True, max_length=255, null=True, verbose_name='Dôvod')),
                ('activities_pass_sk', models.TextField(blank=True, max_length=255, null=True, verbose_name='Aktivity PASS SK')),
                ('responsible', models.CharField(blank=True, choices=[('Salih Yüksekol', 'Dodávateľske NEMECKO: Salih Yüksekol'), ('Giuseppe Verzi', 'NEMECKO Plasty: Giuseppe Verzi'), ('Giuseppe Verzi', 'NEMECKO Polyamidy: Giuseppe Verzi'), ('Giuseppe Verzi', 'NEMECKO Gumy: Giuseppe Verzi'), ('Marek Stach', 'POĽSKO Gumy Marek Stach, Łukasz Jachlewski.'), ('Grzegorz Wacławski', 'POĽSKO Kovové rúrky Grzegorz Wacławski, Paweł Fejdasz'), ('Sanja Ilič', 'BOSNA: Sanja Ilič')], max_length=255, null=True, verbose_name='Zodpovedný')),
                ('created_by', models.CharField(blank=True, choices=[('Geletka', 'Geletka'), ('Staňa', 'Staňa'), ('Pamula', 'Pamula'), ('Spielmann', 'Spielmann'), ('Kaščáková', 'Kaščáková'), ('Augustin', 'Augustin')], max_length=255, null=True, verbose_name='Vytvoril')),
                ('quantity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Počet kusov')),
                ('complaint_status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stav reklamácie')),
                ('note', models.TextField(blank=True, max_length=255, null=True, verbose_name='Poznámka')),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_internal_complaints', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_internal_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('external_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='complaints.externalcomplaint')),
                ('internal_complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='complaints.internalcomplaint')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.PositiveSmallIntegerField(choices=[(1, 'Create'), (2, 'Update'), (3, 'Delete')])),
                ('changes', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_pk', models.TextField()),
                ('object_repr', models.TextField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_log_entries', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_log_entries', to='contenttypes.contenttype')),
            ],
        ),
    ]
